# Generated by Django 5.1.15 on 2026-03-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_map_url',
            field=models.URLField(blank=True, help_text='S3 URL for file_map storage (prepared, not yet active).', max_length=500, null=True),
        ),
    ]
