# Generated by Django 5.1.15 on 2026-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_file_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='generation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
