# Generated by Django 5.1.15 on 2026-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_chatmessage_generation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_used_model',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
