import type { Scaffold } from "./types";
import { RUNTIME_HELPERS_SCRIPT } from "./runtimeHelpers";

// Pinned to Next 14.2 + React 18.3 for WebContainer stability.
// Next 15.1.x + React 19 triggers the well-known "Expected workStore to exist
// when handling searchParams in a client Page" invariant inside WebContainer,
// because React 19's async context isn't fully wired up in the turbopack/webpack
// SSR path that WebContainer serves. Next 14.2 + React 18.3 has no such issue
// and supports App Router, Server/Client components, next/link, next/script.
const PACKAGE_JSON = {
  name: "preview-project",
  private: true,
  scripts: {
    dev: "next dev -H 0.0.0.0 -p 3000",
    build: "next build",
    start: "next start",
  },
  dependencies: {
    next: "14.2.23",
    react: "^18.3.1",
    "react-dom": "^18.3.1",
    "lucide-react": "^0.460.0",
  },
  devDependencies: {
    "@types/node": "^22.10.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    typescript: "^5.6.0",
    tailwindcss: "^3.4.17",
    postcss: "^8.4.49",
    autoprefixer: "^10.4.20",
  },
};

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Allow any images; useful for Unsplash placeholder URLs.
  images: { remotePatterns: [{ protocol: "https", hostname: "**" }] },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "Cross-Origin-Embedder-Policy", value: "credentialless" },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
`;

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`;

const POSTCSS_CONFIG = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

const GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

// Base layout — provided by the scaffold and NOT regenerated by the AI
// (enforced via prompt override). Injects the Dokiflux runtime helpers so
// navigation + error tracking work inside the preview iframe.
const LAYOUT_TSX = `import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Preview",
};

const RUNTIME_HELPERS = ${JSON.stringify(RUNTIME_HELPERS_SCRIPT)};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="root">{children}</div>
        <Script
          id="dokiflux-runtime-helpers"
          strategy="beforeInteractive"
        >
          {RUNTIME_HELPERS}
        </Script>
      </body>
    </html>
  );
}
`;

const TSCONFIG = {
  compilerOptions: {
    target: "ES2020",
    lib: ["dom", "dom.iterable", "esnext"],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    noEmit: true,
    esModuleInterop: true,
    module: "esnext",
    moduleResolution: "bundler",
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: "preserve",
    incremental: true,
    plugins: [{ name: "next" }],
    paths: { "@/*": ["./*"] },
  },
  include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  exclude: ["node_modules"],
};

const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

export const nextjsScaffold: Scaffold = {
  framework: "nextjs",
  // Next.js App Router mounts user files at container root (no src/ prefix).
  // The AI generates /app/page.tsx → we write app/page.tsx directly.
  userFilesRoot: "",
  devCommand: ["npm", "run", "dev"],
  devServerLabel: "Next dev server",
  baseFiles: {
    "package.json": JSON.stringify(PACKAGE_JSON, null, 2),
    "next.config.js": NEXT_CONFIG,
    "tailwind.config.js": TAILWIND_CONFIG,
    "postcss.config.js": POSTCSS_CONFIG,
    "tsconfig.json": JSON.stringify(TSCONFIG, null, 2),
    "next-env.d.ts": NEXT_ENV_DTS,
    "app/globals.css": GLOBALS_CSS,
    "app/layout.tsx": LAYOUT_TSX,
  },
};
