# Generated by Django 5.1.15 on 2026-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userplan',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
