# Generated by Django 5.1.15 on 2026-03-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_stripe_fields_to_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
