# Generated by Django 5.1.15 on 2026-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='file_map_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of project file_map BEFORE this generation (for restore).', null=True),
        ),
    ]
