# Generated by Django 5.1.15 on 2026-03-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generation_file_map_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('no_changes', 'No Changes')], default='pending', max_length=20),
        ),
    ]
