# Generated by Django 5.1.15 on 2026-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_add_result_file_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='is_autofix',
            field=models.BooleanField(default=False),
        ),
    ]
