# Generated by Django 5.1.15 on 2026-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_add_is_autofix'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='chat_history_cache',
            field=models.JSONField(blank=True, help_text='Cached chat_history for background task execution.', null=True),
        ),
    ]
